### PR TITLE
Problem: Can't annotate

### PR DESCRIPTION
**Pull request by betatim**
Solution: load hypothes.is js from the web.

This seems to work for me, but totally hacky. Wonder who we could get to help us out who actually understands JS and electron.

### CODE REVIEW

**Comment by RaoOfPhysics** [comment]
@betatim: Since the project is meant to be a learning exercise, let's learn! :D

Should I merge this PR instead of #2? Can you take a look at my comments there first?

**Comment by betatim** [comment]
Merge #2 then #3 

And then `npm install` and `npm run start`. I created an annotation on the first word of the title, hopefully you can see that.

**Comment by RaoOfPhysics** [comment]
Ok, will merge. Btw, this is what this branch's version looks like when I do `npm run start`:

screen shot 2016-03-05 at 11 06 13

screen shot 2016-03-05 at 11 06 24

screen shot 2016-03-05 at 11 06 26

**Comment by betatim** [comment]
Jupp, this is what it looks like for me. Sad that you don't see the annotation I made :cry:

**Comment by RaoOfPhysics** [comment]
Yeah, the annotation doesn't appear. :(

**Comment by betatim** [comment]
https://hypothes.is/stream?q=user:betatim shows the annotation. Is there a way to figure out what the "canonical URL" for the PDF is? I think that is how hypothes.is attaches annotations to things.

**Comment by RaoOfPhysics** [comment]
I'm not sure one needs URLs for annotating PDFs. See https://hypothes.is/blog/synchronizing-annotations-between-local-and-remote-pdfs/

**Comment by betatim** [comment]
If you have the same webpage at multiple URLs you can put the following in the `<head>`

```
<link rel="canonical" href="http://everware.xyz/lhcb-paris15">
```

in all the copies at different URLs/hostnames and the will all see the same annotations. Adding something like this to `viewer.html` didn't work though.

**Pull request merged**
