### PR TITLE
Problem: There is no app

### PR DESCRIPTION
**Pull request by betatim**
Solution: Create a basic app that opens a window and renders a single page PDF

### CODE REVIEW

**Comment by RaoOfPhysics** [comment]
@betatim: Wow, you are amazing! I told you about the idea and a few hours later you have something to play around with? :D

Ok, before I merge the PR, I wanted to confirm a few things:

When I ran `npm install` within the directory, I got these warnings:

``` bash
npm WARN prefer global coffee-script@1.10.0 should be installed with -g
npm WARN prefer global typescript@1.5.3 should be installed with -g
```

After it installed the app, it also spat out:

``` bash
npm WARN huomata@0.0.1 No repository field.
npm WARN huomata@0.0.1 No license field.
```

Also, when I ran `npm run start`, this is what the window looked like:

firefox - - screen shot 5 mar 2016 10 48 34

Is that what I should've expected to see?

Thanks, once again!

(P.S.: I was actually thinking of using [Photon](http://photonkit.com/) instead of Electron. What do you think of that option before we proceed even further?)

**Comment by betatim** [comment]
Yes that is what you should see. Ugly but shows the pdf :smile:

I know nothing about electron or photon or any of this JS. So I can't give any advice on switching or not. I would stick with electron mainly because @rgbkrk is my JS guru and he uses electron for `nteract`

I didn't get the coffee script warnings but I do get:

```
npm WARN huomata@0.0.1 No repository field.
npm WARN huomata@0.0.1 No license field.
```

which I think is because we should be defining some fields in `package.json` that we aren't

**Comment by RaoOfPhysics** [comment]
Ok, let's test it out and see how it goes! :D

**Comment by RaoOfPhysics** [comment]
> I didn't get the coffee script warnings […]

Maybe because you already have them installed? Anyway…

**Comment by rgbkrk** [comment]
Those warnings crop up because electron-compile bundles typescript and coffeescript. Since it's only using them as a library, this is fine. The warning is in place so that people don't run into running problems at the cli.

**Comment by rgbkrk** [comment]
Wow Photon is slick. I glanced at it before and wasn't nearly impressed as today. It's built on top of Electron, so the question is if you want the magic it provides (seems like a good choice to me). You'll be writing all JS, CSS, HTML either way. :smile:

**Comment by RaoOfPhysics** [comment]
What say @betatim? Stick with Electron or switch to Photon?

**Comment by rgbkrk** [comment]
Photon is effectively a set of templates, you could either copy over the latest and learn from what's there or build on top of the templates: https://github.com/connors/photon#whats-included

**Comment by RaoOfPhysics** [comment]
Thanks, @rgbkrk! :D

**Comment by betatim** [comment]
I don't have much of an opinion. Once we figure out how to use the PDF fingerprint, I would say this is a good minimum viable solution to the problem of shared PDF annotation. Needs some menu items etc. 

Then we can dive into discussing making a new front-end for hypothesis for which I'd advocate [react](https://facebook.github.io/react/) and the ecosystem around it (just so I don't have to hold even more JS jargon in my head simultaneously) So I don't know how much we could copy. For sure we could "copy" by  reading their stuff and then rebuilding.

We'd have to find what plays best with continuing to use pdf.js' viewer which is all html and JS with promises. Keeping the UI exactly like the one people are used to is good I think (and it is pretty hard work to build a good PDF reader UI).

**Comment by RaoOfPhysics** [comment]
I wouldn't advocate changing the UI, but we'll need menu items, as you say: `Open File`, `Close File` etc.

**Pull request merged**
